"""Additive schema migrations for CIPHER evidence, RAG and Vision intelligence."""
from .db import get_db

SQLITE = [
"""CREATE TABLE IF NOT EXISTS rag_documents (id TEXT PRIMARY KEY, case_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, filename TEXT NOT NULL, sha256 TEXT, page_count INTEGER DEFAULT 0, chunk_count INTEGER DEFAULT 0, embedding_provider TEXT, embedding_model TEXT, extraction_method TEXT, status TEXT DEFAULT 'READY', error_message TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')))""",
"""CREATE TABLE IF NOT EXISTS rag_chunks (id TEXT PRIMARY KEY, case_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, document_id TEXT, page_number INTEGER, chunk_index INTEGER NOT NULL, text TEXT NOT NULL, source_reference TEXT, embedding_json TEXT, embedding_provider TEXT, embedding_model TEXT, active INTEGER DEFAULT 1, content_hash TEXT, created_at TEXT DEFAULT (datetime('now')))""",
"""CREATE TABLE IF NOT EXISTS face_profiles (id INTEGER PRIMARY KEY AUTOINCREMENT, case_id INTEGER NOT NULL, entity_id INTEGER, display_name TEXT NOT NULL, username TEXT, source_label TEXT DEFAULT 'AUTHORIZED_CASE_GALLERY', latitude REAL, longitude REAL, address_text TEXT, source_evidence_id INTEGER, image_path TEXT NOT NULL, embedding_json TEXT NOT NULL, embedding_engine TEXT NOT NULL DEFAULT 'insightface-arcface', model_version TEXT NOT NULL DEFAULT 'buffalo_l', active INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT (datetime('now')))""",
"""CREATE TABLE IF NOT EXISTS face_matches (id TEXT PRIMARY KEY, case_id INTEGER NOT NULL, evidence_id INTEGER, face_profile_id INTEGER, candidate_entity_id INTEGER, similarity REAL NOT NULL, model_name TEXT, status TEXT DEFAULT 'PENDING', source_reference TEXT, created_at TEXT DEFAULT (datetime('now')), reviewed_at TEXT, reviewed_by TEXT)""",
"""CREATE TABLE IF NOT EXISTS evidence_observations (id TEXT PRIMARY KEY, case_id INTEGER NOT NULL, evidence_id INTEGER NOT NULL, entity_id INTEGER, location_id INTEGER, event_id INTEGER, observation_type TEXT NOT NULL, confidence REAL DEFAULT 0.0, verification_status TEXT DEFAULT 'PENDING', source_reference TEXT, details_json TEXT, created_at TEXT DEFAULT (datetime('now')))""",
]
POSTGRES = [
"""CREATE TABLE IF NOT EXISTS rag_documents (
    id TEXT PRIMARY KEY,
    case_id INTEGER NOT NULL,
    evidence_id INTEGER NOT NULL,
    filename TEXT NOT NULL,
    sha256 TEXT,
    page_count INTEGER DEFAULT 0,
    chunk_count INTEGER DEFAULT 0,
    embedding_provider TEXT,
    embedding_model TEXT,
    extraction_method TEXT,
    status TEXT DEFAULT 'READY',
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)""",

"""CREATE TABLE IF NOT EXISTS rag_chunks (
    id TEXT PRIMARY KEY,
    case_id INTEGER NOT NULL,
    evidence_id INTEGER NOT NULL,
    document_id TEXT,
    page_number INTEGER,
    chunk_index INTEGER NOT NULL,
    text TEXT NOT NULL,
    source_reference TEXT,
    embedding_json TEXT,
    embedding_provider TEXT,
    embedding_model TEXT,
    active INTEGER DEFAULT 1,
    content_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)""",

"""CREATE TABLE IF NOT EXISTS face_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    entity_id INTEGER,
    display_name TEXT NOT NULL,
    username TEXT,
    source_label TEXT DEFAULT 'AUTHORIZED_CASE_GALLERY',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address_text TEXT,
    source_evidence_id INTEGER,
    image_path TEXT NOT NULL,
    embedding_json TEXT NOT NULL,
    embedding_engine TEXT NOT NULL DEFAULT 'insightface-arcface',
    model_version TEXT NOT NULL DEFAULT 'buffalo_l',
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)""",

"""CREATE TABLE IF NOT EXISTS face_matches (
    id TEXT PRIMARY KEY,
    case_id INTEGER NOT NULL,
    evidence_id INTEGER,
    face_profile_id BIGINT,
    candidate_entity_id INTEGER,
    similarity DOUBLE PRECISION NOT NULL,
    model_name TEXT,
    status TEXT DEFAULT 'PENDING',
    source_reference TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ,
    reviewed_by TEXT
)""",

"""CREATE TABLE IF NOT EXISTS evidence_observations (
    id TEXT PRIMARY KEY,
    case_id INTEGER NOT NULL,
    evidence_id INTEGER NOT NULL,
    entity_id INTEGER,
    location_id INTEGER,
    event_id INTEGER,
    observation_type TEXT NOT NULL,
    confidence DOUBLE PRECISION DEFAULT 0.0,
    verification_status TEXT DEFAULT 'PENDING',
    source_reference TEXT,
    details_json TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)"""
]

def _cols(conn, table):
    try:
        rows=conn.execute(f"PRAGMA table_info({table})").fetchall()
        return {str(r[1]) for r in rows}
    except Exception:
        try:
            rows=conn.execute("SELECT column_name FROM information_schema.columns WHERE table_name=%s",(table,)).fetchall()
            return {str(r[0]) for r in rows}
        except Exception:
            return set()

def _reconcile_face_profiles(conn, is_pg=False):
    """Reconcile the canonical face gallery schema without dropping existing data.

    Older builds could already have ``display_name`` while still missing newer
    provenance/embedding columns.  Every required column is therefore checked
    independently on every startup.
    """
    cols = _cols(conn, "face_profiles")
    if not cols:
        return

    # If an empty legacy table exists with no canonical display_name column,
    # replace it with the canonical schema. Never drop a non-empty table.
    if "display_name" not in cols:
        try:
            count = conn.execute("SELECT COUNT(*) AS c FROM face_profiles").fetchone()[0]
        except Exception:
            count = 0
        if count == 0:
            conn.execute("DROP TABLE face_profiles")
            conn.execute(SQLITE[2] if not is_pg else POSTGRES[2])
            cols = _cols(conn, "face_profiles")

    additions = {
        "case_id": "BIGINT" if is_pg else "INTEGER",
        "entity_id": "BIGINT" if is_pg else "INTEGER",
        "display_name": "TEXT",
        "username": "TEXT",
        "source_label": "TEXT DEFAULT 'AUTHORIZED_CASE_GALLERY'",
        "latitude": "DOUBLE PRECISION" if is_pg else "REAL",
        "longitude": "DOUBLE PRECISION" if is_pg else "REAL",
        "address_text": "TEXT",
        "source_evidence_id": "BIGINT" if is_pg else "INTEGER",
        "image_path": "TEXT",
        "embedding_json": "TEXT",
        "embedding_engine": "TEXT DEFAULT 'insightface-arcface'",
        "model_version": "TEXT DEFAULT 'buffalo_l'",
        "active": "INTEGER DEFAULT 1",
        "created_at": "TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP" if is_pg else "TEXT DEFAULT (datetime('now'))",
    }
    cols = _cols(conn, "face_profiles")
    for column, column_type in additions.items():
        if column not in cols:
            try:
                conn.execute(f"ALTER TABLE face_profiles ADD COLUMN {column} {column_type}")
            except Exception:
                # Keep startup resilient; the API will expose a concrete schema
                # error if a database engine refuses a particular alteration.
                pass

def _reconcile_columns(conn,is_pg=False):
    # face_matches is intentionally text UUID keyed; it is independent from the
    # integer face_profiles table and stores every Vision candidate/review link.
    if is_pg:
        try:
            conn.execute("ALTER TABLE rag_chunks ALTER COLUMN document_id TYPE TEXT USING document_id::text")
        except Exception:
            pass
    for table, additions in {
      'rag_documents': {
        'embedding_model':'TEXT', 'extraction_method':'TEXT', 'error_message':'TEXT',
      },
      'rag_chunks': {
        'embedding_model':'TEXT', 'active':'INTEGER DEFAULT 1', 'content_hash':'TEXT',
      },
      'face_matches': {'id':'TEXT','case_id':'BIGINT' if is_pg else 'INTEGER','evidence_id':'BIGINT' if is_pg else 'INTEGER','face_profile_id':'BIGINT' if is_pg else 'INTEGER','candidate_entity_id':'BIGINT' if is_pg else 'INTEGER','similarity':'DOUBLE PRECISION' if is_pg else 'REAL','model_name':'TEXT','status':'TEXT DEFAULT \'PENDING\'','source_reference':'TEXT','created_at': 'TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP' if is_pg else "TEXT DEFAULT (datetime('now'))",'reviewed_at':'TIMESTAMPTZ' if is_pg else 'TEXT','reviewed_by':'TEXT'},
      'evidence_observations': {'id':'TEXT','case_id':'BIGINT' if is_pg else 'INTEGER','evidence_id':'BIGINT' if is_pg else 'INTEGER','entity_id':'BIGINT' if is_pg else 'INTEGER','location_id':'BIGINT' if is_pg else 'INTEGER','event_id':'BIGINT' if is_pg else 'INTEGER','observation_type':'TEXT','confidence':'DOUBLE PRECISION DEFAULT 0' if is_pg else 'REAL DEFAULT 0','verification_status':"TEXT DEFAULT 'PENDING'",'source_reference':'TEXT','details_json':'TEXT','created_at':'TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP' if is_pg else "TEXT DEFAULT (datetime('now'))"}
    }.items():
        cols=_cols(conn,table)
        for c,t in additions.items():
            if c not in cols:
                try: conn.execute(f'ALTER TABLE {table} ADD COLUMN {c} {t}')
                except Exception: pass

def init_extensions():
    conn=get_db(); is_pg=bool(getattr(conn,'is_postgres',False))
    try:
        for sql in (POSTGRES if is_pg else SQLITE): conn.execute(sql)
        _reconcile_face_profiles(conn,is_pg)
        _reconcile_columns(conn,is_pg)
        for sql in [
            "CREATE INDEX IF NOT EXISTS idx_rag_chunks_case ON rag_chunks(case_id, evidence_id, active)",
            "CREATE INDEX IF NOT EXISTS idx_rag_chunks_document ON rag_chunks(document_id)",
            "CREATE INDEX IF NOT EXISTS idx_rag_documents_case ON rag_documents(case_id, evidence_id)",
            "CREATE INDEX IF NOT EXISTS idx_face_matches_case ON face_matches(case_id, status)",
            "CREATE INDEX IF NOT EXISTS idx_observations_case ON evidence_observations(case_id, evidence_id)",
        ]: 
            try: conn.execute(sql)
            except Exception: pass
        conn.commit()
    finally: conn.close()
